services:
  - type: web
    name: homecenter-price-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ENABLE_PLAYWRIGHT
        value: "true"
    healthCheckPath: /health
